# Generated by Django 5.2.7 on 2025-11-03 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('full_name', models.CharField(max_length=255, verbose_name='Họ và tên')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('role', models.CharField(choices=[('CUSTOMER', 'Khách hàng'), ('ADMIN', 'Quản trị viên')], default='CUSTOMER', max_length=50, verbose_name='Vai trò')),
                ('account_status', models.CharField(choices=[('ACTIVE', 'Hoạt động'), ('DISABLED', 'Vô hiệu hóa')], default='ACTIVE', max_length=50, verbose_name='Trạng thái tài khoản')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CharityProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tên chương trình')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('image', models.ImageField(upload_to='charity_programs/', verbose_name='Hình ảnh')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Mục tiêu')),
                ('status', models.CharField(choices=[('ACTIVE', 'Đang hoạt động'), ('PAUSED', 'Tạm dừng'), ('COMPLETED', 'Kết thúc')], default='ACTIVE', max_length=50, verbose_name='Trạng thái')),
            ],
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('otp_code', models.CharField(max_length=6, verbose_name='Mã OTP')),
                ('expires_at', models.DateTimeField(verbose_name='Thời gian hết hạn')),
                ('is_used', models.BooleanField(default=False, verbose_name='Đã sử dụng')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tên hộp quà')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá bán')),
                ('charity_percentage', models.DecimalField(decimal_places=2, help_text='Ví dụ: 10.00 cho 10%', max_digits=5, verbose_name='Phần trăm từ thiện')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Hình ảnh đại diện')),
                ('status', models.CharField(choices=[('FOR_SALE', 'Đang bán'), ('SOLD_OUT', 'Hết hàng'), ('DELETED', 'Đã xóa')], default='FOR_SALE', max_length=50, verbose_name='Trạng thái')),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên ưu đãi')),
                ('points_required', models.PositiveIntegerField(verbose_name='Số điểm yêu cầu')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá trị giảm')),
                ('voucher_type', models.CharField(choices=[('PERCENTAGE', 'Theo %'), ('FIXED_AMOUNT', 'Theo số tiền')], max_length=50, verbose_name='Loại ưu đãi')),
                ('conditions', models.TextField(verbose_name='Điều kiện sử dụng')),
            ],
        ),
        migrations.CreateModel(
            name='LovePointBalance',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='point_balance', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
                ('current_balance', models.PositiveIntegerField(default=0, verbose_name='Tổng điểm hiện tại')),
            ],
        ),
        migrations.CreateModel(
            name='ContentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('featured_image', models.ImageField(upload_to='content_posts/', verbose_name='Ảnh đại diện')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng')),
                ('post_type', models.CharField(choices=[('BLOG', 'Blog'), ('NEWS', 'Tin tức'), ('REPORT', 'Báo cáo Minh bạch')], max_length=50, verbose_name='Loại bài viết')),
                ('author', models.ForeignKey(limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Tác giả')),
            ],
        ),
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Số tiền giải ngân')),
                ('disbursed_at', models.DateField(verbose_name='Ngày giải ngân')),
                ('recipient_partner', models.CharField(max_length=255, verbose_name='Đối tác nhận')),
                ('notes', models.TextField(verbose_name='Ghi chú')),
                ('proof_link', models.FileField(blank=True, null=True, upload_to='disbursements_proof/', verbose_name='Link chứng từ')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursements', to='store.charityprogram', verbose_name='Chương trình')),
            ],
        ),
        migrations.CreateModel(
            name='LovePointHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('EARNED', 'Cộng điểm'), ('SPENT', 'Trừ điểm')], max_length=50, verbose_name='Loại giao dịch')),
                ('points_changed', models.IntegerField(verbose_name='Số điểm thay đổi')),
                ('reason', models.CharField(max_length=255, verbose_name='Lý do')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày giao dịch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_history', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=20, unique=True, verbose_name='Mã đơn hàng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đặt')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tổng tiền')),
                ('payment_method', models.CharField(choices=[('COD', 'Thanh toán khi nhận hàng'), ('ONLINE', 'Thanh toán trực tuyến')], max_length=50, verbose_name='Phương thức thanh toán')),
                ('order_status', models.CharField(choices=[('NEW', 'Mới'), ('PENDING', 'Chờ xác nhận'), ('SHIPPING', 'Đang giao'), ('DELIVERED', 'Đã giao'), ('CANCELLED', 'Đã hủy')], default='NEW', max_length=50, verbose_name='Trạng thái đơn hàng')),
                ('donate_voucher', models.BooleanField(default=False, verbose_name='Quyên góp ưu đãi')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
        ),
        migrations.CreateModel(
            name='DonationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Số tiền quyên góp')),
                ('donation_type', models.CharField(choices=[('FROM_PRODUCT', 'Từ % Sản phẩm'), ('FROM_VOUCHER', 'Từ Ưu đãi 10%')], max_length=50, verbose_name='Loại quyên góp')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='store.charityprogram', verbose_name='Chương trình')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='store.order', verbose_name='Đơn hàng')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_status', models.CharField(choices=[('NEW', 'Mới'), ('PENDING', 'Chờ xác nhận'), ('SHIPPING', 'Đang giao'), ('DELIVERED', 'Đã giao'), ('CANCELLED', 'Đã hủy')], max_length=50, verbose_name='Trạng thái mới')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian cập nhật')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='store.order', verbose_name='Đơn hàng')),
                ('updated_by', models.ForeignKey(limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
            ],
        ),
        migrations.CreateModel(
            name='RedeemedOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_code', models.CharField(max_length=50, unique=True, verbose_name='Mã ưu đãi đã cấp')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đổi')),
                ('usage_status', models.CharField(choices=[('NOT_USED', 'Chưa dùng'), ('USED', 'Đã dùng'), ('EXPIRED', 'Hết hạn')], default='NOT_USED', max_length=50, verbose_name='Trạng thái sử dụng')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redeemed_offers', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redeemed_instances', to='store.voucher', verbose_name='Ưu đãi')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='applied_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.redeemedoffer', verbose_name='Mã ưu đãi đã áp dụng'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(verbose_name='Điểm sao (1-5)')),
                ('comment', models.TextField(verbose_name='Bình luận')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('display_status', models.CharField(choices=[('VISIBLE', 'Đang hiển thị'), ('HIDDEN', 'Bị ẩn')], default='VISIBLE', max_length=50, verbose_name='Trạng thái hiển thị')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product', verbose_name='Sản phẩm')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=255, verbose_name='Họ tên người nhận')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('province', models.CharField(max_length=100, verbose_name='Tỉnh/Thành')),
                ('district', models.CharField(max_length=100, verbose_name='Quận/Huyện')),
                ('ward', models.CharField(max_length=100, verbose_name='Phường/Xã')),
                ('street_address', models.CharField(max_length=255, verbose_name='Địa chỉ chi tiết')),
                ('is_default', models.BooleanField(default=False, verbose_name='Là địa chỉ mặc định')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.shippingaddress', verbose_name='Địa chỉ giao hàng'),
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Số lượng')),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá tại thời điểm mua')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='store.order', verbose_name='Đơn hàng')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product', verbose_name='Sản phẩm')),
            ],
            options={
                'unique_together': {('order', 'product')},
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Sản phẩm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
